### ISSUE TITLE
Allergies for check-in tab

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#114]
We need a place on Chums to add Allergies of a kid and if they want them to be printed on the tag or not.

**Comment by Laaight** [comment]
@mbyrdLCS @jzongker  Would this most likely be on the person profile and maybe only if the person is marked as Child?

**Comment by mbyrdLCS** [comment]
Allergies Are nice to know if an adult has them to so I would not say limit it to children

**Comment by jzongker** [comment]
Let's just add the field on person records regardless of age and let churches decide when they want to fill it out.

**Comment by jzongker** [comment]
I think we just need a single field for the allergies and don't need a separate "Print / Do not print" option.  I don't see any need for churches to enter this if they're not going to print it.  If it's present, we'll print it.

We need to limit this field length to something that is reasonably printable.  Maybe 20 characters?  We need it to say `Peanuts` not `Aiden is allergic to peanuts, but they're ok in small quantities.  There is an EpiPen in the diaper bag in case of an emergency.` in order to be printable.  The additional details will need to be communicated via another means.

**Comment by mbyrdLCS** [comment]
Some allergies / problems are not wanted on the tag but teachers need to know if there is a special need. Such as ADHD we don't want that printed but we need that information. If do not print is selected a simple ! Could be added to the tag so they know there is an issue

**Comment by jzongker** [comment]
@mbyrdLCS and I were able to discuss offline and come to a solution.

Let's add a "Name tag notes" field and limit it to 20 characters.  Whatever the church enters here will be printed on the name tags.

There are additional scenarios where private notes need to be kept (ADHD, pickup issues, etc).  We already have the option for generic notes on people records which are limited to church staff.  We'll use those for these needs.  

If the church chooses to do so they can also discretely add a "!", "+" or other symbol to the name tag notes field to indicate there are issues to be aware of without printing the details.

**Comment by Laaight** [comment]
@jzongker Got it, I'm working on it!

**Comment by jzongker** [comment]
The field for entering the allergies is complete with https://github.com/LiveChurchSolutions/MembershipApi/pull/70 and https://github.com/LiveChurchSolutions/ChumsApp/pull/228 .  We still need to actually print them which is open issue #132
