### ISSUE TITLE
Can not Paste or Center Content

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#139]
https://user-images.githubusercontent.com/65249159/230140620-1af964f0-d9b1-4da9-ab40-aa2c49e27afb.mp4

**Comment by jzongker** [comment]
I think this is a rich text vs plain text issue.  If you paste into Notepad or TextEdit to remove the formatting first and then copy/paste into the editor, I think it'll work.

**Comment by mbyrdLCS** [comment]
Ok I did try that but still the same problem I do not have a problem until I add the email address if I take.com and save it works if not it just disappears when I save it.  Also did you see the center issue this seems to be the problem across the board

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS The center doesn't seem to be an issue now, I guess it might have been fixed. The Paste issue was because of the .com at the end of the Gmail, but that's fixed now, so pasting that whole thing from (https://www.frciola.com/contact.html) will work.

https://www.loom.com/share/33c58daf78b6463297e4fac55194f17a?sid=c5bc14a4-7294-4aff-a1b5-a020e3034785

After pasting that whole thing, you might see a '?' before the Gmail, but that's because the website has an invisible character before the Gmail, so the editor is just putting a '?' instead of that character.
