### ISSUE TITLE
member directory opt-out option

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#37]
We need to have an option for people to opt-out of being in the member directory. Someone is a member of the church but for what ever reason they do not want their information showing up in the member directory.   Right now we just have to mark them as visitors

**Comment by jzongker** [comment]
Let's add a checkbox to the user profile screen.  This preference will be stored on the `people` record rather than the `users` record and only affect the currently selected church, not all churches the user has a profile on.

The membershipApi query to load members will need to be updated to check this new flag.  This does not affect the load all people query that is used for chums admins, just the public member directory.

**Comment by PhotoPaul** [comment]
@jzongker @mbyrdLCS  I did the following:
https://github.com/LiveChurchSolutions/ChumsApp/commit/9815454dc2ee6349ab779f24e12d35b8f634c58f
https://github.com/LiveChurchSolutions/ChumsApp/commit/d0801dffe0f4c5fda3d1604323f166e9c4e8ea6a
https://github.com/LiveChurchSolutions/MembershipApi/commit/a1b550f8b19edd7261cbdc4893bf9070a1beb823

The new UI looks like this:
![image](https://user-images.githubusercontent.com/3471804/213650554-cd7c3349-54c6-4519-8edb-18f7a0bf96eb.png)
