### ISSUE TITLE
Can not create tabs in the b1 app

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#57]
https://user-images.githubusercontent.com/65249159/212938718-55df6ca0-8d01-4888-84b3-750717052444.mp4

Micheal will Report to terry@livechurchsolutions.org when this is fixed

**Comment by PhotoPaul** [comment]
The problem seems to be that the "ironwood" church is selected by default upon logging in [src/pages/[sdSlug]/login.tsx] and as a result you are trying to add a new Tab to a church you don't have the right access to.

I'll wait on @jzongker to fix this because he must have done this for debugging reasons, but a quick workaround in the meantime is to manually click on your name, church, and then select the church you want to add the tab to. Now you can go ahead a add the new tab. Please note that if you refresh the page the wrong church is selected again and you have to follow the same process.
