### ISSUE TITLE
New Giving Stripe Option 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#69]
Ad an option not by default but an Option that force users to pay the stripe fees in the giving app.

**Comment by jzongker** [comment]
To clarify this should be an admin setting in chums that churches can turn on.  If the church turns it on, rather than it prompting the user if they'd like to cover the donation fees, they are automatically applied.  So if I user chooses to donate $50, it'll show $50 + $1.70 processing fees = $51.70.  

Let's include a link to a new article on https://support.churchapps.org/ explaining these fees.
